"""
synthetic_temp_calibration.py
=============================================================
Pashu-Sutra — Synthetic Temperature Calibration Model
=============================================================

PURPOSE:
    Generate a synthetic dataset of (neck_surface_temp, ambient_temp,
    time_of_day) → rectal_core_temp pairs using veterinary literature
    parameters, then train a linear regression model and output the
    constants ready to embed in the JavaScript app.

LITERATURE BASIS:
    - McDowell & Hillman (1959): Cattle neck surface temp is 1.5–2.5°C
      below rectal temp under normal conditions
    - Gebremedhin et al. (2010): Ambient temp raises surface-core offset
      by ~0.04°C per °C rise in ambient above 20°C
    - Beatty et al. (2006): Afternoon peak adds ~0.3°C to core temp
      compared to early morning
    - Breed factor: HF cattle run ~0.2°C warmer than indigenous breeds

HOW TO RUN:
    pip install numpy pandas scikit-learn matplotlib
    python synthetic_temp_calibration.py

OUTPUT:
    1. synthetic_cattle_temp.csv  — generated dataset  
    2. model_report.txt           — R², coefficients, JS formula
    3. calibration_plot.png       — scatter plot (actual vs predicted)
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

# ─── Reproducibility ────────────────────────────────────────────────
np.random.seed(42)
N = 2000  # synthetic sample count

# ─── Generate Input Features ────────────────────────────────────────

# Neck surface temperature: 35.5°C – 39.0°C (realistic collar reading)
neck_temp = np.random.uniform(35.5, 39.0, N)

# Ambient temperature: 10°C – 42°C (covers Indian climate, all seasons)
ambient_temp = np.random.uniform(10, 42, N)

# Time of day: 0–23 hours (affects core temp by up to 0.4°C)
hour_of_day = np.random.uniform(0, 23, N)

# Breed: 0 = indigenous (Gir, Sahiwal), 1 = exotic/HF crossbreed
breed = np.random.randint(0, 2, N)

# ─── Physiologically-Grounded Calibration Formula ────────────────────
#
# Based on literature:
#   core = neck + BASE_OFFSET 
#          + AMBIENT_EFFECT * max(0, ambient - 20)
#          + TIME_EFFECT * sin(π * hour / 12)   [afternoon peak]
#          + BREED_EFFECT * breed
#          + Gaussian noise
#
BASE_OFFSET    = 1.85   # °C — mean neck-to-core offset (Hillman 1959)
AMBIENT_EFFECT = 0.040  # °C per °C above 20°C ambient (Gebremedhin 2010)
TIME_EFFECT    = 0.30   # °C — diurnal amplitude (Beatty 2006)
BREED_EFFECT   = 0.20   # °C — HF breeds run warmer (Collier 2012)
NOISE_STD      = 0.15   # °C — biological variability / sensor noise

ambient_contribution = AMBIENT_EFFECT * np.maximum(0, ambient_temp - 20)
time_contribution    = TIME_EFFECT * np.sin(np.pi * hour_of_day / 12)
breed_contribution   = BREED_EFFECT * breed
noise                = np.random.normal(0, NOISE_STD, N)

rectal_temp = (
    neck_temp
    + BASE_OFFSET
    + ambient_contribution
    + time_contribution
    + breed_contribution
    + noise
)

# Clip to realistic rectal range: 37.5°C – 41.5°C
rectal_temp = np.clip(rectal_temp, 37.5, 41.5)

# ─── Build DataFrame ────────────────────────────────────────────────
df = pd.DataFrame({
    'neck_temp':    neck_temp,
    'ambient_temp': ambient_temp,
    'hour_of_day':  hour_of_day,
    'breed':        breed,
    'rectal_temp':  rectal_temp,
})

df.to_csv('synthetic_cattle_temp.csv', index=False)
print(f"✅ Dataset saved: synthetic_cattle_temp.csv ({N} rows)")
print(df.describe().round(3))

# ─── Train Linear Regression Model ──────────────────────────────────
features = ['neck_temp', 'ambient_temp', 'hour_of_day', 'breed']
X = df[features].values
y = df['rectal_temp'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2  = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"\n📊 Model Performance:")
print(f"   R² Score  : {r2:.4f}")
print(f"   MAE       : {mae:.4f} °C")

# ─── Extract Coefficients ────────────────────────────────────────────
coef = model.coef_
intercept = model.intercept_

print(f"\n🔢 Linear Regression Coefficients:")
for name, c in zip(features, coef):
    print(f"   {name:20s}: {c:.6f}")
print(f"   {'intercept':20s}: {intercept:.6f}")

# ─── Generate JavaScript Formula ─────────────────────────────────────
c_neck    = coef[0]
c_ambient = coef[1]
c_hour    = coef[2]
c_breed   = coef[3]

js_formula = f"""
// ─── Temperature Calibration — Embedded in databaseService.js ───────
// Generated by synthetic_temp_calibration.py
// R² = {r2:.4f}, MAE = {mae:.4f}°C

/**
 * Convert neck surface temperature to estimated core body temperature.
 * @param {{number}} neckTemp    - DS18B20 reading (°C)
 * @param {{number}} ambientTemp - outdoor/shed temperature (°C)
 * @param {{number}} hour        - hour of day (0–23)
 * @param {{number}} breed       - 0 = indigenous, 1 = HF/crossbreed
 * @returns {{number}} estimated rectal (core) temperature in °C
 */
export function estimateCoreTemp(neckTemp, ambientTemp = 28, hour = 12, breed = 0) {{
  const core = (
    {c_neck:.6f} * neckTemp +
    {c_ambient:.6f} * ambientTemp +
    {c_hour:.6f} * hour +
    {c_breed:.6f} * breed +
    {intercept:.6f}
  );
  // Clamp to physiologically valid range
  return Math.min(Math.max(core, 37.5), 41.5);
}}

// Example usage in DashboardScreen:
// const coreTemp = estimateCoreTemp(neckReading, ambientTemp, new Date().getHours(), 0);
// Alert if coreTemp > 39.5 (fever threshold)
"""

print(js_formula)

# ─── Save Report ─────────────────────────────────────────────────────
with open('model_report.txt', 'w') as f:
    f.write("PASHU-SUTRA TEMPERATURE CALIBRATION MODEL REPORT\n")
    f.write("=" * 50 + "\n\n")
    f.write(f"Dataset Size : {N} synthetic samples\n")
    f.write(f"R² Score     : {r2:.4f}\n")
    f.write(f"MAE          : {mae:.4f} °C\n\n")
    f.write("Literature References:\n")
    f.write("  - McDowell & Hillman (1959): base neck-core offset = 1.85°C\n")
    f.write("  - Gebremedhin et al. (2010): ambient contribution\n")
    f.write("  - Beatty et al. (2006): diurnal time-of-day effect\n")
    f.write("  - Collier et al. (2012): breed effect\n\n")
    f.write("Coefficients:\n")
    for name, c in zip(features, coef):
        f.write(f"  {name}: {c:.6f}\n")
    f.write(f"  intercept: {intercept:.6f}\n\n")
    f.write("JavaScript formula:\n")
    f.write(js_formula)

print("✅ Report saved: model_report.txt")

# ─── Plot: Actual vs Predicted ────────────────────────────────────────
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.3, s=10, color='steelblue', label='Predictions')
plt.plot([37.5, 41.5], [37.5, 41.5], 'r--', linewidth=2, label='Perfect fit')
plt.xlabel('Actual Rectal Temp (°C)', fontsize=12)
plt.ylabel('Predicted Core Temp (°C)', fontsize=12)
plt.title(f'Pashu-Sutra: Neck → Core Temp Calibration\nR²={r2:.4f}  MAE={mae:.4f}°C', fontsize=13)
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('calibration_plot.png', dpi=150)
print("✅ Plot saved: calibration_plot.png")
plt.show()
